== FIDM
Управление контейнерами docker.
:toc:


== Установка

=== Зависимости

* Linux
* Bash
* link:http://docker.io[Docker]

=== Установка

FIDM - это скрипт на bash. Для установки достаточно его скопировать в каталог из $PATH и дать права на запуск:

-----
FIDM_VER=0.1 && curl -o /usr/local/bin/fidm -SL https://github.com/LeKovr/fidm/releases/download/${FIDM_VER}/fidm.sh \
  && chmod +x /usr/local/bin/fidm
-----

== Использование

=== Команды

-----
fidm COMMAND CONFIG[.yml] [all] [var=value]
-----

Где: 

COMMAND :: одна из
  build   ::: docker build
  start   ::: docker run или docker start для текущего и связанных контейнеров
  stop    ::: docker stop для текущего контейнера (stop CONFIG all - для текущего и связанных)
  rm      ::: docker rm для текущего контейнера (rm CONFIG all - для текущего и связанных)
  init    ::: создать пример файла конфигурации

CONFIG    :: файл конфигурации в формате YML

all       :: расширение действия команды на связанные контейнеры, используется в командах "stop" и "rm"

var=value :: перезапись значений параметров fidm из файла конфигурации

=== Примеры

-----
# Выполнить docker build с аргументами из файла postgres.yml
fidm build postgres

# Выполнить docker run с аргументами из файла pgws.yml и задать контейнеру суффикс "dev"
# Если такой контейнер уже есть, выполнить для него docker run
fidm start pgws mode=dev

# Остановить контейнер из modperl.yml и все контейнеры, от которых он зависит
fidm stop modperl all
-----

=== Конфигурация

Конфигурация контейнеров размещается в файлах .yml. В одном файле NAME.yml содержатся настройки только одного контейнера (контейнер получает имя NAME). 

* Параметры fidm - строковые значения, которые могут быть переназначены в командной строке fidm (var=value)
* Списки fidm - списки связанных контейнеров, портов, каталогов. Могут быть заданы только в файле настроек
* Аргументы docker run - значения без модификации передаются в вызов docker run

Все параметры с их описаниями можно выгрузить в пример файла конфигурации командой "fidm init NAME"

=== Быстрый старт

Для примера используем контейнеры из проекта link:https://github.com/LeKovr/consup[consup]

-----
$git clone https://github.com/LeKovr/consup.git
$cp -R consup/eg/nginx-static .
$cd samplesite
$fidm start
-----

== Лицензия

The MIT License (MIT)

== Про fig

Первоначально управление контейнерами docker осуществлялось посредством link:http://fig.sh[fig].
Однако, желание что-то изменить, что-то добавить и нежелание использовать для этого python привели к созданию еще одного решения похожей задачи,
которое имеет следующие отличия:

* Конфигурация имеет вычисляемые значения по умолчанию, позволяющие минимизировать файл настроек (вплоть до его отсутствия)
* Несущественные аргументы docker передаются ему напрямую (нет трансляции типа environment -> env), что позволяет поддерживать все текущие и будущие аргументы docker
* Реализован автостарт зависимых контейнеров (с их линковкой или без)

== См. также

Параметры конфигурации с описаниями - см. eg/fidm_rus.yml
